import axios from "axios";
import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import { RootState } from "../store";
import { TpostsState } from "../../types.d/common.types.d";

const initialPostsState: TpostsState = {
  postList: [],
  loading: { status: false, message: "" },
  error: { status: false, message: "" },
};

export const loadPosts = createAsyncThunk(
  "postsSlice/fetchData",
  async (topicId: string) => {
    const resp = await axios.get(
      `${process.env.REACT_APP_API_URL}/api/topic/${topicId}`
    );
    // The value we return becomes the `fulfilled` action payload
    return resp.data;
  }
);

const postsSlice = createSlice({
  name: "posts",
  initialState: initialPostsState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(loadPosts.pending, (state) => {
        state.loading.status = true;
        state.loading.message = "loading posts....";
      })
      .addCase(loadPosts.fulfilled, (state, action) => {
        state.loading.status = false;
        state.loading.message = "";
        state.postList = action.payload.posts;
      })
      .addCase(loadPosts.rejected, (state, action) => {
        state.loading.status = false;
        state.error.status = true;
        state.error.message = action.error.message || "";
      });
  },
});

export const postsData = (state: RootState) => state.postsReducer;
export default postsSlice.reducer;
